# Generated by Django 5.1.3 on 2024-12-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_user_alter_post_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
